import { images } from "../constants";

const PropertyData = {
  data: [
    {
      id: 1,
      description: "Modern apartment with beautiful city views.",
      title: "Cityview Apartment",
      price: 1499,
      image: images.prop1,
      amenities: ['WiFi', 'Pool'],
      totalBedrooms: 3,
      isAvailable: true,
      location: "Downtown, New York",
      rating: 4.2,
      totalRatings: 145,
    },
    {
      id: 2,
      description: "Cozy suburban house near the lake.",
      title: "Lakeside House",
      price: 999,
      image: images.prop2,
      amenities: ['WiFi', 'Balcony', 'Gym'],
      totalBedrooms: 4,
      isAvailable: true,
      location: "Lakeview, Seattle",
      rating: 4.5,
      totalRatings: 89,
    },
    {
      id: 3,
      description: "Spacious villa with private pool and garden.",
      title: "Sunset Villa",
      price: 1999,
      image: images.prop3,
      amenities: ['WiFi', 'Pool'],
      totalBedrooms: 5,
      isAvailable: false,
      location: "Beverly Hills, Los Angeles",
      rating: 4.8,
      totalRatings: 210,
    },
    {
      id: 4,
      description: "Modern apartment in the heart of the city.",
      title: "Urban Heights Apartment",
      price: 1299,
      image: images.prop4,
      amenities: ['WiFi', 'Gym', 'Balcony'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Downtown, New York",
      rating: 4.1,
      totalRatings: 76,
    },
    {
      id: 5,
      description: "Quaint cottage in the mountains, perfect for a getaway.",
      title: "Mountainview Cottage",
      price: 849,
      image: images.prop5,
      amenities: ['WiFi', 'Balcony', 'Parking'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Aspen, Colorado",
      rating: 4.7,
      totalRatings: 58,
    },
    {
      id: 6,
      description: "Luxurious penthouse with panoramic city views.",
      title: "Panorama Penthouse",
      price: 2499,
      image: images.prop6,
      amenities: ['WiFi', 'Pool', 'Parking'],
      totalBedrooms: 4,
      isAvailable: false,
      location: "Midtown, New York",
      rating: 4.9,
      totalRatings: 130,
    },
    {
      id: 7,
      description: "Charming house close to local parks and schools.",
      title: "Parkside Family Home",
      price: 1199,
      image: images.prop7,
      amenities: ['WiFi', 'Gym', 'Balcony'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Greenlake, Seattle",
      rating: 4.3,
      totalRatings: 72,
    },
    {
      id: 8,
      description: "Beachfront house with direct access to the shore.",
      title: "Oceanfront Retreat",
      price: 1899,
      image: images.prop8,
      amenities: ['WiFi', 'Parking', 'Pool'],
      totalBedrooms: 2,
      isAvailable: false,
      location: "Venice Beach, Los Angeles",
      rating: 4.6,
      totalRatings: 96,
    },
    {
      id: 9,
      description: "Rustic cabin in the woods, ideal for nature lovers.",
      title: "Woodland Cabin",
      price: 799,
      image: images.prop9,
      amenities: ['WiFi', 'Gym', 'Balcony'],
      totalBedrooms: 1,
      isAvailable: true,
      location: "Aspen, Colorado",
      rating: 4.4,
      totalRatings: 49,
    },
    {
      id: 10,
      description: "Luxury condo in a high-rise building with great views.",
      title: "Skylight Condo",
      price: 1799,
      image: images.prop10,
      amenities: ['WiFi', 'Gym', 'Pool'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Midtown, New York",
      rating: 4.2,
      totalRatings: 105,
    },
    {
      id: 11,
      description: "Spacious family home in a quiet neighborhood.",
      title: "Hillside Family Home",
      price: 1099,
      image: images.prop11,
      amenities: ['WiFi', 'Gym', 'Parking'],
      totalBedrooms: 4,
      isAvailable: false,
      location: "Greenlake, Seattle",
      rating: 4.3,
      totalRatings: 83,
    },
    {
      id: 12,
      description: "Stylish loft in an artistic downtown area.",
      title: "Downtown Artist Loft",
      price: 1399,
      image: images.prop12,
      amenities: ['WiFi', 'Gym', 'Balcony'],
      totalBedrooms: 1,
      isAvailable: true,
      location: "Downtown, New York",
      rating: 4.5,
      totalRatings: 59,
    },
    {
      id: 13,
      description: "Contemporary house with a stunning outdoor patio.",
      title: "Modern Patio House",
      price: 1599,
      image: images.prop13,
      amenities: ['WiFi', 'Gym', 'Pool'],
      totalBedrooms: 3,
      isAvailable: true,
      location: "Venice Beach, Los Angeles",
      rating: 4.7,
      totalRatings: 109,
    },
    {
      id: 14,
      description: "Luxurious estate with tennis court and large garden.",
      title: "Beverly Estate",
      price: 2999,
      image: images.prop14,
      amenities: ['WiFi', 'Parking', 'Gym'],
      totalBedrooms: 2,
      isAvailable: false,
      location: "Beverly Hills, Los Angeles",
      rating: 4.9,
      totalRatings: 195,
    },
    {
      id: 15,
      description: "Cozy mountain lodge, perfect for a winter retreat.",
      title: "Snowpeak Lodge",
      price: 999,
      image: images.prop15,
      amenities: ['WiFi', 'Balcony'],
      totalBedrooms: 3,
      isAvailable: true,
      location: "Aspen, Colorado",
      rating: 4.6,
      totalRatings: 65,
    },
    // New properties
    {
      id: 16,
      description: "Elegant flat in a vibrant neighborhood.",
      title: "Vibrant City Flat",
      price: 1399,
      image: images.prop1,
      amenities: ['WiFi', 'Gym'],
      totalBedrooms: 1,
      isAvailable: true,
      location: "Downtown, New York",
      rating: 4.3,
      totalRatings: 30,
    },
    {
      id: 17,
      description: "Luxurious home with spacious backyard.",
      title: "Luxury Family Home",
      price: 1999,
      image: images.prop2,
      amenities: ['WiFi', 'Balcony', 'Pool'],
      totalBedrooms: 4,
      isAvailable: false,
      location: "Lakeview, Seattle",
      rating: 4.6,
      totalRatings: 70,
    },
    {
      id: 18,
      description: "Beautiful seaside villa for your getaway.",
      title: "Seaside Villa",
      price: 2499,
      image: images.prop3,
      amenities: ['WiFi', 'Parking', 'Gym'],
      totalBedrooms: 5,
      isAvailable: true,
      location: "Venice Beach, Los Angeles",
      rating: 4.8,
      totalRatings: 110,
    },
    {
      id: 19,
      description: "Charming apartment in a historic district.",
      title: "Charming Historic Apartment",
      price: 1299,
      image: images.prop4,
      amenities: ['WiFi', 'Balcony'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Downtown, New York",
      rating: 4.1,
      totalRatings: 50,
    },
    {
      id: 20,
      description: "Peaceful retreat with mountain views.",
      title: "Mountainview Retreat",
      price: 1599,
      image: images.prop5,
      amenities: ['WiFi', 'Gym', 'Parking'],
      totalBedrooms: 3,
      isAvailable: true,
      location: "Aspen, Colorado",
      rating: 4.5,
      totalRatings: 60,
    },
    {
      id: 21,
      description: "Chic condo with modern finishes.",
      title: "Chic City Condo",
      price: 1899,
      image: images.prop6,
      amenities: ['WiFi', 'Gym', 'Pool'],
      totalBedrooms: 2,
      isAvailable: false,
      location: "Midtown, New York",
      rating: 4.2,
      totalRatings: 45,
    },
    {
      id: 22,
      description: "Cozy apartment with garden access.",
      title: "Garden View Apartment",
      price: 999,
      image: images.prop7,
      amenities: ['WiFi', 'Balcony'],
      totalBedrooms: 1,
      isAvailable: true,
      location: "Greenlake, Seattle",
      rating: 4.4,
      totalRatings: 55,
    },
    {
      id: 23,
      description: "Spacious townhouse in a family-friendly area.",
      title: "Family-Friendly Townhouse",
      price: 1299,
      image: images.prop8,
      amenities: ['WiFi', 'Parking', 'Gym'],
      totalBedrooms: 3,
      isAvailable: true,
      location: "Beverly Hills, Los Angeles",
      rating: 4.5,
      totalRatings: 80,
    },
    {
      id: 24,
      description: "Rustic mountain cabin perfect for winter sports.",
      title: "Mountain Sports Cabin",
      price: 799,
      image: images.prop9,
      amenities: ['WiFi', 'Gym'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Aspen, Colorado",
      rating: 4.3,
      totalRatings: 40,
    },
    {
      id: 25,
      description: "Luxurious villa with pool and scenic views.",
      title: "Scenic Luxury Villa",
      price: 2999,
      image: images.prop10,
      amenities: ['WiFi', 'Parking', 'Pool'],
      totalBedrooms: 5,
      isAvailable: false,
      location: "Venice Beach, Los Angeles",
      rating: 4.9,
      totalRatings: 120,
    },
    {
      id: 26,
      description: "Stylish loft near downtown attractions.",
      title: "Downtown Stylish Loft",
      price: 1399,
      image: images.prop11,
      amenities: ['WiFi', 'Gym', 'Balcony'],
      totalBedrooms: 1,
      isAvailable: true,
      location: "Downtown, New York",
      rating: 4.6,
      totalRatings: 75,
    },
    {
      id: 27,
      description: "Elegant estate with a large garden.",
      title: "Elegant Family Estate",
      price: 2499,
      image: images.prop12,
      amenities: ['WiFi', 'Balcony', 'Gym'],
      totalBedrooms: 4,
      isAvailable: false,
      location: "Beverly Hills, Los Angeles",
      rating: 4.8,
      totalRatings: 150,
    },
    {
      id: 28,
      description: "Cozy bungalow with modern amenities.",
      title: "Cozy Modern Bungalow",
      price: 999,
      image: images.prop13,
      amenities: ['WiFi', 'Gym'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Lakeview, Seattle",
      rating: 4.4,
      totalRatings: 35,
    },
    {
      id: 29,
      description: "Charming cottage near the beach.",
      title: "Charming Beach Cottage",
      price: 1899,
      image: images.prop14,
      amenities: ['WiFi', 'Parking', 'Gym'],
      totalBedrooms: 3,
      isAvailable: true,
      location: "Venice Beach, Los Angeles",
      rating: 4.7,
      totalRatings: 95,
    },
    {
      id: 30,
      description: "Modern villa with ocean views.",
      title: "Ocean View Villa",
      price: 2999,
      image: images.prop15,
      amenities: ['WiFi', 'Gym'],
      totalBedrooms: 5,
      isAvailable: true,
      location: "Aspen, Colorado",
      rating: 4.5,
      totalRatings: 80,
    },
    {
      id: 31,
      description: "Lovely apartment with city skyline views.",
      title: "Skyline View Apartment",
      price: 1199,
      image: images.prop1,
      amenities: ['WiFi', 'Gym'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Downtown, New York",
      rating: 4.5,
      totalRatings: 60,
    },
    {
      id: 32,
      description: "Luxury condo with stunning beach access.",
      title: "Luxury Beach Condo",
      price: 2499,
      image: images.prop2,
      amenities: ['WiFi', 'Balcony'],
      totalBedrooms: 4,
      isAvailable: false,
      location: "Venice Beach, Los Angeles",
      rating: 4.8,
      totalRatings: 100,
    },
    {
      id: 33,
      description: "Spacious apartment close to local amenities.",
      title: "Spacious Local Apartment",
      price: 1399,
      image: images.prop3,
      amenities: ['WiFi', 'Parking', 'Gym'],
      totalBedrooms: 3,
      isAvailable: true,
      location: "Midtown, New York",
      rating: 4.4,
      totalRatings: 70,
    },
    {
      id: 34,
      description: "Contemporary house with elegant design.",
      title: "Elegant Contemporary House",
      price: 1799,
      image: images.prop4,
      amenities: ['WiFi', 'Gym'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Lakeview, Seattle",
      rating: 4.2,
      totalRatings: 40,
    },
    {
      id: 35,
      description: "Charming family home in a quiet neighborhood.",
      title: "Charming Family Home",
      price: 999,
      image: images.prop5,
      amenities: ['WiFi', 'Parking'],
      totalBedrooms: 1,
      isAvailable: true,
      location: "Greenlake, Seattle",
      rating: 4.3,
      totalRatings: 55,
    },
    {
      id: 36,
      description: "Luxurious apartment with all amenities.",
      title: "Luxurious All-Inclusive Apartment",
      price: 1999,
      image: images.prop6,
      amenities: ['WiFi', 'Gym', 'Pool'],
      totalBedrooms: 5,
      isAvailable: false,
      location: "Midtown, New York",
      rating: 4.9,
      totalRatings: 90,
    },
    {
      id: 37,
      description: "Stylish loft with modern design elements.",
      title: "Modern Stylish Loft",
      price: 1299,
      image: images.prop7,
      amenities: ['WiFi', 'Balcony', 'Gym'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Downtown, New York",
      rating: 4.4,
      totalRatings: 80,
    },
    {
      id: 38,
      description: "Beautifully decorated cottage with views.",
      title: "Decorated Cottage Retreat",
      price: 1399,
      image: images.prop8,
      amenities: ['WiFi', 'Gym'],
      totalBedrooms: 3,
      isAvailable: true,
      location: "Aspen, Colorado",
      rating: 4.5,
      totalRatings: 35,
    },
    {
      id: 39,
      description: "Charming suburban home with lovely backyard.",
      title: "Suburban Home Retreat",
      price: 999,
      image: images.prop9,
      amenities: ['WiFi', 'Balcony'],
      totalBedrooms: 2,
      isAvailable: true,
      location: "Lakeview, Seattle",
      rating: 4.1,
      totalRatings: 50,
    },
    {
      id: 40,
      description: "Luxurious estate with amazing architecture.",
      title: "Luxurious Estate",
      price: 2999,
      image: images.prop10,
      amenities: ['WiFi', 'Gym', 'Parking'],
      totalBedrooms: 5,
      isAvailable: false,
      location: "Beverly Hills, Los Angeles",
      rating: 4.9,
      totalRatings: 140,
    },
  ],
};

export default PropertyData;
